name: Build and Deploy to docker hub

on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the repo
        uses: actions/checkout@v2
      - name: Log into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./docker/Dockerfile.user
          tags: alim490/ci-cd:latest
      - name: Verify Pushed image
        run: docker pull alim490/ci-cd:latest
    